name: Build Check

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Gradle permissions
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew assembleDebug