name: Build Check

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          mkdir -p app/
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Create secret.properties file
        run: |
          cat <<EOF > secret.properties
          API_KEY="${{ secrets.API_KEY }}"
          BASE_URL="${{ secrets.BASE_URL }}"
          EOF

      - name: Grant Gradle permissions
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew assembleDebug --stacktrace