name: Firebase CD - Distribute APK

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Decode google‑services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          mkdir -p app/
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > app/google-services.json

      - name: Check google-services.json
        run: |
          ls -la app/
          head -n 5 app/google-services.json

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: List APK files
        run: find . -name "*.apk"

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Decode Firebase service account key
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT" | base64 --decode > "${{ github.workspace }}/firebase-service-account.json"

      - name: Set GOOGLE_APPLICATION_CREDENTIALS env var
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-service-account.json" >> $GITHUB_ENV

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
            --app 1:1038392982530:android:1187ed24f9e5829c76bb1b \
            --release-notes "Automated release from GitHub Actions" \
            --groups "release-testers"