name: Firebase CD - Distribute APK

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    name: Build & Deploy Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        run: |
          echo "$GOOGLE_SERVICES_JSON" > app/google-services.json

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Decode Firebase service account key
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${{ github.workspace }}/firebase-service-account.json"

      - name: Set GOOGLE_APPLICATION_CREDENTIALS env var
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-service-account.json" >> $GITHUB_ENV

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
            --app 1:148511152938:android:b42a76ac7812fa20795c53 \
            --release-notes "Automated release from GitHub Actions"
