name: Firebase CD - Distribute APK

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    name: Build & Deploy Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
            --app 1:148511152938:android:b42a76ac7812fa20795c53
            --token "${{ secrets.FIREBASE_TOKEN }}"
